### PR TITLE
Refactor: ioutil to io

### PR DESCRIPTION
**Pull request by tanryberdi**
- Changed ioutil package to io package

See #17

### CODE REVIEW

**Comment by tanryberdi** [comment]
@vaguecoder I think before this task, we need to solve #3, because I got `undefined: io.ReadAll`, this messages gives for old version go, wdyt?

**Comment by vaguecoder** [comment]
@tanryberdi Since #25 is merged in master, please rebase with your latest commit from master into this.

**Comment by tanryberdi** [comment]
> @tanryberdi Since #25 is merged in master, please rebase with your latest commit from master into this.

done, rebased

**Review by vaguecoder — APPROVED** [review]
LGTM

**Comment by vaguecoder** [comment]
Thanks @tanryberdi

**Pull request merged**
